name: release-please

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # Optional so CI checks trigger on the PR:
          token: ${{ secrets.ACTIONS_PAT }}
          # Single-package Node repo:
          release-type: node
